mac/ubuntu portable Makefile

diff --git a/os/Makefile b/os/Makefile
--- a/os/Makefile
+++ b/os/Makefile
@@ -1,4 +1,3 @@
-
 KERNEL_IMAGE=kernel
 
 OBJS = \
@@ -6,13 +5,26 @@ OBJS = \
 	main.o \
 	uart.o \
 
-CC=riscv64-unknown-elf-gcc
+ifndef TOOLPREFIX
+TOOLPREFIX := $(shell if riscv64-unknown-elf-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
+	then echo 'riscv64-unknown-elf-'; \
+	elif riscv64-linux-gnu-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
+	then echo 'riscv64-linux-gnu-'; \
+	elif riscv64-unknown-linux-gnu-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
+	then echo 'riscv64-unknown-linux-gnu-'; \
+	else echo "***" 1>&2; \
+	echo "*** Error: Couldn't find a riscv64 version of GCC/binutils." 1>&2; \
+	echo "*** To turn off this error, run 'gmake TOOLPREFIX= ...'." 1>&2; \
+	echo "***" 1>&2; exit 1; fi)
+endif
+
+CC=$(TOOLPREFIX)gcc
 CFLAGS = -Wall -Werror -fno-omit-frame-pointer -ggdb -gdwarf-2
 CFLAGS += -MD -mcmodel=medany -I.
 CFLAGS += -ffreestanding -fno-common -nostdlib -mno-relax
-LD=riscv64-unknown-elf-ld
+LD=$(TOOLPREFIX)ld
 LDFLAGS = -z max-page-size=4096
-OBJDUMP=riscv64-unknown-elf-objdump
+OBJDUMP=$(TOOLPREFIX)objdump
 
 all: $(KERNEL_IMAGE)
 
@@ -28,10 +40,17 @@ $(KERNEL_IMAGE): $(OBJS)
 
 
 QEMU=qemu-system-riscv64
-RUN=$(QEMU) -machine virt -cpu rv64 -smp 1 -s -bios none -kernel $(KERNEL_IMAGE) -m 128M -nographic 
+RUN=$(QEMU) -machine virt -cpu rv64 -smp 1 -bios none -kernel $(KERNEL_IMAGE) -m 128M -nographic 
 
 qemu: all 
 	$(RUN)
 
 clean:
 	rm -rf $(OBJS) $(KERNEL_IMAGE) *.asm *.d *.o
+
+GDB_PORT=1234
+
+debug: all
+	@echo "*** Now run 'gdb-multiarch $(KERNEL_IMAGE)' in another window"
+	@echo "*** Once in, run 'target remote localhost:$(GDB_PORT)'"
+	$(RUN) -gdb tcp::$(GDB_PORT) -S
